language: python
python:
  - "3.7"

jobs:
  include:
    - name: "lint: backend"
      before_script:
        - cd backend
        - pip install pipenv
        - pipenv install --dev --system
      script:
        - black --check .
        - flake8 .
