version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: deja_brew
      MYSQL_DATABASE: deja_brew
    volumes:
      - ./target/db/:/var/lib/mysql

  backend:
    build: backend
    links:
      - database
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URI: mysql://database

  frontend:
    build: frontend
    ports:
      - "8080:80"
    links:
      - backend
