"""Add cafe table

Revision ID: 6dcc1f903f83
Revises: d9ab7e33c942
Create Date: 2020-03-07 11:13:10.929211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcc1f903f83'
down_revision = 'd9ab7e33c942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=63), nullable=True),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe')
    # ### end Alembic commands ###
