"""Initial migration

Revision ID: d9ab7e33c942
Revises: 
Create Date: 2020-03-07 11:06:21.118236

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9ab7e33c942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=63), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.String(255), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=63), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cup_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='cupsize'), nullable=False),
    sa.Column('coffee_type', sa.Enum('LATTE', 'CAPPUCCINO', 'FLAT_WHITE', 'LONG_BLACK', 'MOCHA', 'HOT_CHOC', 'MATCHA', 'ESPRESSO', name='coffeetype'), nullable=False),
    sa.Column('milk_type', sa.Enum('REGULAR', 'SKIM', 'SOY', 'ALMOND', 'OAT', name='milktype'), nullable=False),
    sa.Column('extras', sa.String(255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'READY', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
